### ISSUE TITLE
angular-cli-builders:custom-webpack-server not work

### ISSUE THREAD

**Issue by AlexDaSoul** [meltedspark/angular-cli-builders#1] opened 2018-07-03 17:31 UTC
Hi! angular-cli-builders:custom-webpack-server finished with errors

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(webpackConfigPath).

if remove webpackConfigPath then the next error is next property and more and more and more
when remove all except for main. ng serve finished as ng buld, not start dev-server

**Comment by arjanburggraaf** [comment] 2018-07-03 17:56
Hi @meltedspark, thanks you for providing this small but very useful builder!
I ran into the same issue.

I noticed that 'webpackConfigPath' is missing in: src/custom-webpack/server/schema.json.
But 'webpackConfigPath' is present in src/custom-webpack/browser/schema.json.

**Comment by meltedspark** [comment] 2018-07-03 21:37
Hi, thanks for reporting this issue.

@arjanburggraaf indeed `webpackConfigPath` was missing from the schema, it's fixed in version `1.0.3`. Thank you for reporting the root cause.

@AlexDaSoul the reason it complains about such properties as index, styles, scripts etc. is that these properties are not supported in the original `@angular-devkit/build-angular:server` and, as README states, this builder is an extension that adds one more entry `webpackConfigPath`.  
The README was confusing though, as it had these properties in the sample angular.json for server. This is fixed now.
Check out the full server [schema](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/server/schema.d.ts) and properties description.  
Also, you may find [this ](https://stackoverflow.com/questions/50401415/angular-cli-6-ng-build-doesnt-produce-server-bundles) and [this](https://github.com/angular/angular-cli/issues/10417) useful for building universal app.

**Comment by meltedspark** [comment] 2018-07-03 21:38
I'm reopening this issue as a reminder for myself to write a test but generally **it is fixed in build `1.0.3`**

**Closed** 2018-07-06 12:51 UTC
Labels: fixed, test:required
